const languageStrings = {
  en: {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page, you can nagivate forward or back. You can also vote on and bookmark items or you can say exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page, ',
      SORTED_PAGE: 'sorted by %s.',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
    }
  },
  'en-US': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page, you can nagivate forward or back. You can also vote on and bookmark items or you can say exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page, ',
      SORTED_PAGE: 'sorted by %s.',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
    }
  },
  'en-GB': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page, you can nagivate forward or back. You can also vote on and bookmark items or you can say exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page, ',
      SORTED_PAGE: 'sorted by %s.',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
    }
  },
  'en-AU': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page, you can nagivate forward or back. You can also vote on and bookmark items or you can say exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page, ',
      SORTED_PAGE: 'sorted by %s.',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
    }
  },
  'en-IN': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page, you can nagivate forward or back. You can also vote on and bookmark items or you can say exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page, ',
      SORTED_PAGE: 'sorted by %s.',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
    }
  },
  'en-CA': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page, you can nagivate forward or back. You can also vote on and bookmark items or you can say exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page, ',
      SORTED_PAGE: 'sorted by %s.',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
    }
  }
}

module.exports = {
  languageStrings
}
