const languageStrings = {
  en: {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page sorted by new, hot, controversial and rising. You can then navigate forward or back using voice or the display. You can vote on and bookmark items using the on screen buttons. You can quit this skill by saying stop or exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page sorted by hot? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page',
      SORTED_PAGE: ', sorted by %s.',
      PAGE_ACTION: 'You can now swipe through posts on screen, or you can say next and back to navigate. What would you like to do?',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
      FALLBACK_MESSAGE: 'Sorry, I\'m not sure how to help you with that, please say \'help\' to hear what you can do.',
      FALLBACK_REPROMT: 'Say help for more information on what you can do.',
    }
  },
  'en-US': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page sorted by new, hot, controversial and rising. You can then navigate forward or back using voice or the display. You can vote on and bookmark items using the on screen buttons. You can quit this skill by saying stop or exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page sorted by hot? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page',
      SORTED_PAGE: ', sorted by %s.',
      PAGE_ACTION: 'You can now swipe through posts on screen, or you can say next and back to navigate. What would you like to do?',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
      FALLBACK_MESSAGE: 'Sorry, I\'m not sure how to help you with that, please say \'help\' to hear what you can do.',
      FALLBACK_REPROMT: 'Say help for more information on what you can do.',
    }
  },
  'en-GB': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page sorted by new, hot, controversial and rising. You can then navigate forward or back using voice or the display. You can vote on and bookmark items using the on screen buttons. You can quit this skill by saying stop or exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page sorted by hot? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page',
      SORTED_PAGE: ', sorted by %s. ',
      PAGE_ACTION: 'You can now swipe through posts on screen, or you can say next and back to navigate. What would you like to do?',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
      FALLBACK_MESSAGE: 'Sorry, I\'m not sure how to help you with that, please say \'help\' to hear what you can do.',
      FALLBACK_REPROMT: 'Say help for more information on what you can do.',
    }
  },
  'en-AU': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page sorted by new, hot, controversial and rising. You can then navigate forward or back using voice or the display. You can vote on and bookmark items using the on screen buttons. You can quit this skill by saying stop or exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page sorted by hot? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page',
      SORTED_PAGE: ', sorted by %s.',
      PAGE_ACTION: 'You can now swipe through posts on screen, or you can say next and back to navigate. What would you like to do?',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
      FALLBACK_MESSAGE: 'Sorry, I\'m not sure how to help you with that, please say \'help\' to hear what you can do.',
      FALLBACK_REPROMT: 'Say help for more information on what you can do.',
    }
  },
  'en-IN': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page sorted by new, hot, controversial and rising. You can then navigate forward or back using voice or the display. You can vote on and bookmark items using the on screen buttons. You can quit this skill by saying stop or exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page sorted by hot? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page',
      SORTED_PAGE: ', sorted by %s.',
      PAGE_ACTION: 'You can now swipe through posts on screen, or you can say next and back to navigate. What would you like to do?',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
      FALLBACK_MESSAGE: 'Sorry, I\'m not sure how to help you with that, please say \'help\' to hear what you can do.',
      FALLBACK_REPROMT: 'Say help for more information on what you can do.',
    }
  },
  'en-CA': {
    translation: {
      SKILL_NAME: 'Reddit Viewer',
      WELCOME_MESSAGE: 'Welcome to %s. You can ask me to show your front page... Now, what can I help you with?',
      WELCOME_REPROMPT: 'For instructions on what you can do, say help me.',
      HELP_MESSAGE: 'You can ask me to open your front page sorted by new, hot, controversial and rising. You can then navigate forward or back using voice or the display. You can vote on and bookmark items using the on screen buttons. You can quit this skill by saying stop or exit. Now, what can I help you with?',
      HELP_REPROMPT: 'Why not ask me to show your front page sorted by hot? Now, what can I help you with?',
      STOP_MESSAGE: 'Goodbye!',
      REPEAT_MESSAGE: 'Try saying repeat.',
      ERROR_MESSAGE: 'I\'m sorry, I encountered an error. ',
      REPROMPT_MESSAGE: 'Try asking me to show your front page.',
      HINT_MESSAGE: ['Alexa, Next', 'Alexa, Back'],
      APL_REQUIRED: 'This device does not have a screen output, please use another device.',
      ACCOUNT_UNLINKED: 'You need to link your Reddit account to use this skill.',
      FRONT_PAGE: 'Here is your front page',
      SORTED_PAGE: ', sorted by %s.',
      PAGE_ACTION: 'You can now swipe through posts on screen, or you can say next and back to navigate. What would you like to do?',
      BOOKMARK_ADD_MESSAGE: 'Bookmark added.',
      BOOKMARK_REMOVE_MESSAGE: 'Bookmark removed.',
      UPVOTE_ADD_MESSAGE: 'Upvoted.',
      UPVOTE_REMOVE_MESSAGE: 'Removed Upvote.',
      FEATURE_UNAVILALBE: 'This feature is currently unavailable by voice, please use the on-screen buttons',
      FALLBACK_MESSAGE: 'Sorry, I\'m not sure how to help you with that, please say \'help\' to hear what you can do.',
      FALLBACK_REPROMT: 'Say help for more information on what you can do.',
    }
  }
}

module.exports = {
  languageStrings
}
